# File: data_pasien.py

data_pasien = [
    {
        "id": "bhsa6812",
        "nama": "John Doe",
        "dob": "1990-05-15",
        "gender": "Male",
        "diagnosis": "Hypertension",
        "checkup": {"checkupDate": "2024-02-27", "result": "Normal"},
    },
    {
        "id": "xyz123",
        "nama": "Mikaela",
        "dob": "1989-09-22",
        "gender": "Female",
        "diagnosis": "Flu",
        "checkup": {"checkupDate": "2024-03-05", "result": "Stable"},
    },
    {
        "id": "abc789",
        "nama": "Emily Johnson",
        "dob": "1985-07-10",
        "gender": "Female",
        "diagnosis": "Allergy",
        "checkup": {"checkupDate": "2024-03-01", "result": "Improving"},
    },
    {
        "id": "pqr456",
        "nama": "Michael Smith",
        "dob": "1978-12-03",
        "gender": "Male",
        "diagnosis": "Diabetes",
        "checkup": {"checkupDate": "2024-02-28", "result": "Stable"},
    },
    {
        "id": "def234",
        "nama": "Sophia Martinez",
        "dob": "1995-04-18",
        "gender": "Female",
        "diagnosis": "Migraine",
        "checkup": {"checkupDate": "2024-03-03", "result": "Improving"},
    },
    {
        "id": "jkl012",
        "nama": "Amanda Johnson",
        "dob": "1992-11-20",
        "gender": "Female",
        "diagnosis": "Common Cold",
        "checkup": {"checkupDate": "2024-03-10", "result": "Stable"},
    },
    {
        "id": "mno345",
        "nama": "David Smith",
        "dob": "1987-06-25",
        "gender": "Male",
        "diagnosis": "Influenza",
        "checkup": {"checkupDate": "2024-03-12", "result": "Improving"},
    },
    {
        "id": "pqr678",
        "nama": "Isabella Brown",
        "dob": "1994-04-14",
        "gender": "Female",
        "diagnosis": "Headache",
        "checkup": {"checkupDate": "2024-03-14", "result": "Stable"},
    },
    {
        "id": "stu901",
        "nama": "Christopher Davis",
        "dob": "1980-09-05",
        "gender": "Male",
        "diagnosis": "Allergic Rhinitis",
        "checkup": {"checkupDate": "2024-03-16", "result": "Normal"},
    },
    {
        "id": "vwx234",
        "nama": "Olivia Taylor",
        "dob": "1998-02-18",
        "gender": "Female",
        "diagnosis": "Stomach Flu",
        "checkup": {"checkupDate": "2024-03-18", "result": "Stable"},
    },
]
